### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by TomFaulkner** [hertg/egpu-switcher#10]
I don't see a change log under releases. Is there one somewhere else? Given that this is important to my system being usable it would be nice to see what changes were made outside of having to do a git blame.

Thanks for your hard work on this, btw.

**Comment by hertg** [comment]
@TomFaulkner 
Good point, I'll do my best to add a changelog to the releases page in future versions.
As @dmurtari mentioned, theres an existing changelog for previous releases under `debian/changelog`.

In general, i don't do any "breaking changes", as the goal of this project is pretty straight forward.

I'll leave the issue open as a personal reminder.

**Comment by TomFaulkner** [comment]
Thanks!
