### ISSUE TITLE
intel arc support

### ISSUE THREAD

**Issue by naturalkind** [hertg/egpu-switcher#110]
Hello, it is possible to use your repository to connect intel arc a770?

**Comment by hertg** [comment]
I am not up to date on the Intel GPUs but theoretically it should, have you tried already? Would be great to have some feedback on that.

**Comment by naturalkind** [comment]
I am thinking about the expediency of this experiment, how much am I ready for a chain of quests to achieve my goal: launching the kandinsky 2.1 diffusion model :)

**Comment by hertg** [comment]
I'm gonna close this, you can reopen if you find any issue with Intel GPU support. Let me know if you come around to give it a try. :)
