### ISSUE TITLE
Ubuntu 19.10: unable to add repo. 

### ISSUE THREAD

**Issue by elmono74** [hertg/egpu-switcher#12]
The repository 'http://ppa.launchpad.net/hertg/egpu-switcher/ubuntu eoan Release' does not have a Release file.
Updating from such a repository can't be done securely, and is therefore disabled by default.

I get the above error when trying to add the repo to my system.

**Comment by hertg** [comment]
Yes, my last release was before 19.10 came out.
I just re-released  the latest version for 19.10 Eoan, please try again and report back if anything goes wrong.
