### ISSUE TITLE
Prevent "No such file or directory" output in switch command

### ISSUE THREAD

**Issue by hertg** [hertg/egpu-switcher#15]
Some users might see the following output when executing the `egpu-switcher switch egpu` command.

```
ls: cannot access '/sys/bus/pci/devices/0000:09:00.0/drm/card[0-9]*/card[0-9]*-*/status': No such file or directory
cat: '/sys/bus/pci/devices/0000:09:00.0/drm/card[0-9]*/card[0-9]*-*/status': No such file or directory
```

That's not an error, but just an output of the script while it checks if those directories exist.
It would be more user-friendly to hide this output from the end-user.

Related to PR #14

**Comment by ewagner12** [comment]
Hey I have a fix to this as well as a couple other enhancements. Do you want me to make another PR?

**Comment by hertg** [comment]
@ewagner12 Sure, keep them coming 😄 
I'll have a look at the issue #5 once i get time. I'd like to solve that one before releasing a new version.
Just in case you are wondering why i haven't published a release with your changes.

**Comment by hertg** [comment]
This was fixed in 92bd495fd0de11dad1fa35f463c58df517be5ac4

**Comment by hertg** [comment]
@ewagner12 I released a version including your PRs today, but i also added some additional stuff and refactored a lot of the code. Would be great if you could update and check if your code still works as expected, as i can't really test it on my system. I hope that i didn't break anything :wink:

**Comment by ewagner12** [comment]
@hertg Thanks for the release! I updated to 0.11.1 on my system and found no issues with the refactored code. Seems to be working as normal.
