### ISSUE TITLE
Unable to update in Ubuntu 18.04.3

### ISSUE THREAD

**Issue by tominglis** [hertg/egpu-switcher#26]
I have not tried using egpu-switcher yet, so I don't think there are any config files. But at the moment it is failing to update.

sudo egpu-switcher cleanup --hard
[info] Starting cleanup process
[info] Removing configuration files (--hard)
Failed to stop egpu.service: Unit egpu.service not loaded.

sudo apt full-upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages have been kept back:
  libpoppler85
The following packages will be upgraded:
  egpu-switcher
1 to upgrade, 0 to newly install, 0 to remove and 1 not to upgrade.
Need to get 0 B/8,288 B of archives.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
(Reading database ... 315582 files and directories currently installed.)
Preparing to unpack .../egpu-switcher_0.12.0_amd64.deb ...
[info] Starting cleanup process
Failed to stop egpu.service: Unit egpu.service not loaded.
dpkg: warning: old egpu-switcher package pre-removal script subprocess returned error exit status 5
dpkg: trying script from the new package instead ...
[info] Starting cleanup process
Failed to stop egpu.service: Unit egpu.service not loaded.
dpkg: error processing archive /var/cache/apt/archives/egpu-switcher_0.12.0_amd64.deb (--unpack):
 new egpu-switcher package pre-removal script subprocess returned error exit status 5
Errors were encountered while processing:
 /var/cache/apt/archives/egpu-switcher_0.12.0_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by hertg** [comment]
Thanks for your report.

This seems to be the same issue as described in #25.
I will address it there and mark this one as duplicate.
