### ISSUE TITLE
awk error in Manjaro linux

### ISSUE THREAD

**Issue by mobius41** [hertg/egpu-switcher#27]
When running gswitch setup the following error occurs in Manjaro linux

- `sudo gswitch setup`
```awk: cmd. line:1: warning: regexp escape sequence `\"' is not a known regexp operator```

It may be related to different versions of gawk.

- `gawk -V`:
`GNU Awk 5.0.1, API: 2.0 (GNU MPFR 4.0.2, GNU MP 6.1.2)`

**Comment by hertg** [comment]
In your command it says `gswitch` instead of `egpu-switcher`.
Also, there is no awk command in the egpu-switcher script.
I guess you are in the wrong repo. 

Did you meant to create the issue here? 
https://github.com/karli-sjoberg/gswitch
