### ISSUE TITLE
missing release files for 20.04 focal 

### ISSUE THREAD

**Issue by juicypop** [hertg/egpu-switcher#31]
I just installed your egpu-switcher on latest Ubuntu 20.04 focal release and can confirm it working without any issues my friend :+1: 
It would be nice if you could create the release files for focal on launchpad

To install your egpu-switcher I had to manually edit the apt file to point it to bionic main

**Comment by hertg** [comment]
I just copied the existing binaries to the Focal series on launchpad.
Thanks for the input. The upcoming dist-upgrade will probably go a lot smoother for existing users now 👍
