### ISSUE TITLE
Steam refuses to load when switching back to "internal"

### ISSUE THREAD

**Issue by tominglis** [hertg/egpu-switcher#37]
**Context:**

I have a clean install of Ubuntu 20.04 on my Lenovo ThinkPad T480, with Intel UHD Graphics 620 and the latest UEFI updates.

I have an Akitio Node eGPU chassis with a Sapphire Radeon R9 Nano GPU.

I have an Iiyama G-Master GB2488HSU monitor connected to the laptop via HDMI and the eGPU via DisplayPort.

I installed steam using "sudo apt install -y steam-installer", logged in, and installed a number of games, before I setup and used egpu-switcher. Since setting up egpu-switcher I have run a couple of games using the eGPU.

**Problem:**

When I run "sudo egpu-switcher switch internal", restart the computer, and then login again, I am no longer able to run steam.

It runs the process to check for updates, but when it comes to loading the app itself, it looks like it changes the screen's mode setting, and then fails.

**Evidence:**

myuser@mycomputer:~$ steam
Running Steam on ubuntu 20.04 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Steam client's requirements are satisfied
/home/myuser/.steam/debian-installation/ubuntu12_32/steam -nominidumps -nobreakpad
[2020-05-28 09:55:17] Startup - updater built May 15 2020 03:04:07
[2020-05-28 09:55:17] Verifying installation...
[2020-05-28 09:55:17] Verification complete
STEAM_RUNTIME_HEAVY: ./steam-runtime-heavy
Warning: failed to set thread priority: set failed for 4: -1: setpriority() failed
Warning: failed to set thread priority: set failed for priority 4
Warning: support for elevated priorities is most likely unavailable, suppressing future warnings

**Comment by ewagner12** [comment]
Do you have anything in the file /etc/X11/xorg.conf.internal

**Comment by tominglis** [comment]
I haven't added anything to it. Here's what's in there:

Section "Module"
    Load           "modesetting"
EndSection

Section "Device"
    Identifier     "Device0"
    Driver         "intel"
    BusID          "0:2:0"
    Option         "AllowEmptyInitialConfiguration"
    Option         "AllowExternalGpus" "True"
EndSection

**Comment by tominglis** [comment]
Here's xorg.conf.egpu:

Section "Module"
    Load           "modesetting"
EndSection

Section "Device"
    Identifier     "Device0"
    Driver         "amdgpu"
    BusID          "9:0:0"
    Option         "AllowEmptyInitialConfiguration"
    Option         "AllowExternalGpus" "True"
EndSection

**Comment by hertg** [comment]
@tominglis 
Please see my response in your other issue #36

**Comment by tominglis** [comment]
I can confim that this seems to have resolved the issues I had.
