### ISSUE TITLE
login loop on ubuntu 20.04

### ISSUE THREAD

**Issue by LevytsRoman** [hertg/egpu-switcher#41]
I have a dell xps 13 with dual booted ubuntu and windows. 

I recently reinstalled ubuntu, and after installing egpu switcher started encountering a login loop on startup.

Checking /var/log/Xorg.0.log revealed had an error saying no screen found.
Manually switching to egpu from ttl3 fixes this and allows me to login. 
However I have to do this every time I turn on my laptop.

I have a bios setting enabled that prevents things connected through egpu working in grub, my best guess is that there is some sort of a race condition happening.

Anyway not sure if it's a bug or even fixable, but thought I'd post it here for awareness.

**Comment by hertg** [comment]
This might be a similar problem to issue #45.

Please have a look at the comment i posted there: 
https://github.com/hertg/egpu-switcher/issues/45#issuecomment-656655052

Does changing your `egpu.service` like that resolve your issue?

**Comment by LevytsRoman** [comment]
I ended up enabling bios setting to allow thunderbolt devices before boot, it fixed it for me. 

(Before you think I'm a complete moron, the reason I had it disabled in the first place was because on windows there was a bug that made it reconnect every 3 seconds making it unusable, but I guess an update fixed it or something, so it's fine now.)

**Comment by hertg** [comment]
Alright, good to hear.
I'm closing the issue but mark it with the `knowledge` label, for future troubleshooting.

> Before you think I'm a complete moron, ...

Don't assume that anyone would think that, the Linux/Open-Source community is way friendlier than it's perceived sometimes :)

**Comment by thepearson** [comment]
I had a similar issue after running `apt update` the ubuntu kernel on 20.04. Basically, logging into "Ubuntu" X server (default) would fail and kick me back out to the login screen. Changing my server to Wayland logging in then running `sudo egpu-switcher switch egpu`, logging out, then logging back in to "Ubuntu" X server would work. I had to do this every single login where the egpu was attached.

Enabling the thunderbolt before boot in the bios fixed this for me also. Hopefully, this helps someone else.

**Comment by hertg** [comment]
@thepearson 
Sorry that you had to search through closed issues to find a solution.

I've recently added a [TROUBLESHOOT.md](https://github.com/hertg/egpu-switcher/blob/master/TROUBLESHOOT.md) file to the repo, and mentioned it in the README. 
The solution to enable Pre-Boot ACL is also mentioned in there.

Did you come across that file, or should I place it more prominently somewhere in the README? 
I just want to make sure that people can find that instead of having to search closed issues :)

**Comment by aryoda** [comment]
FYI: In my case (Tuxedo Notebook with Ubuntu) I had the same problem with the login screen loop
but there is no "Pre-Boot ACL" setting in the BIOS.

My solution was to set "Native OS security for TBT" to "disabled" and "(TBT) security level" to "no security" in the BIOS.

My devices connected to the egpu USB hub were then recognized directly after switching on the notebook and the GPU driver in the X11 xorg.conf (`amdgpu` in my case) did work with my external screen connected to the egpu.

Perhaps you could ad this "synonym" to "Pre-Boot ACL" to your `troubleshoot.md` too...

**Comment by hertg** [comment]
@aryoda 
Thanks for your feedback. I didn't mention the option to completely disable thunderbolt security intentionally. If you feel that such a mention would have helped you a lot, then maybe it would be an option to mention it together with a disclaimer:

The solution you found is unfortunately not a "synonym" for the `Pre-Boot ACL` setting mentioned in the troubleshoot notes. Disabling Thunderbolt security should not be done deliberately without knowing the security implications. A site that does a good job of explaining some of the security issues can be found [here](https://thunderclap.io/).

**In my opinion**, completely disabling thunderbolt security should be relatively unproblematic if all of the following apply:
- All disks are fully hardware encrypted, meaning no data can be accessed while the computer is turned off
- Computer is never left running unattended (where other people could have physical access)

If any of the requirements above are **not met**, I believe that completely disabling thunderbolt security is insecure and should be refrained from. Of course, if there is no sensitive data on the computer, or the risk of becoming a target is considered nearly impossible, then disabling all thunderbolt security may be worth the benefits.

I just wanted to put that disclaimer out there. I am a bit paranoid on computer security.
