### ISSUE TITLE
Failed to start EGPU service

### ISSUE THREAD

**Issue by JEdwardsD** [hertg/egpu-switcher#43]
I was using my egpu, shut down, might have unplugged too early (don’t think I did), and when I boot up my computer I’m met with “Failed to start EGPU service“ after I decrypt my drive. Seems to be an endless loop. Plugging in the egpu and booting that way doesn’t solve the problem.

![41CE9B87-1402-4BF7-B06B-305D8C14952F](https://user-images.githubusercontent.com/65467291/86078564-63a90400-ba5c-11ea-922d-08b3e9ce8cf4.jpeg)

**Comment by hertg** [comment]
I haven't seen this error before.
Is there any more information when viewing the `systemctl status egpu.service` or in the `journalctl`?

**Comment by JEdwardsD** [comment]
Ended up reflashing my os on that drive, never solved the issue. ¯\_(ツ)_/¯
