### ISSUE TITLE
Script stops working with NVIDIA Driver 451.48

### ISSUE THREAD

**Issue by hewlett-packard-lovecraft** [hertg/egpu-switcher#46]
I'm on OpenSUSE Tumbleweed. After updating to the latest TW snapshot, which included NVIDIA 451.48, the script stopped working. I tried downgrading to an older kernel, no luck. After I rolled back to an older snapshot, it worked. It seems to be a issue with NVIDIA 451.48. I'm using the git version of the script.

**Comment by hertg** [comment]
Where did you get an NVIDIA Driver 451.48? Is this like an alpha/beta release?

According to NVIDIA the latest one is `450.57` (https://www.nvidia.com/en-us/drivers/unix/).
I just updated my drivers to the latest available for Arch Linux `450.57-2`, and have no issues whatsoever.
