### ISSUE TITLE
line 372: [: too many arguments

### ISSUE THREAD

**Issue by fennifith** [hertg/egpu-switcher#56]
I've actually edited my `xorg.conf.egpu` file from the generated one, so I know this isn't an expected error, but I think it should still be supported - the `grep -Ei "Driver"` command on [L372](https://github.com/hertg/egpu-switcher/blob/a89d62f8c25ed9d12f39a2fa4413801118c9aa49/egpu-switcher#L372) is now returning `amdgpu modesetting`, which bash interprets as two separate parts, breaking the if condition.

My hacky fix was to surround the command in quotes so that bash sees it as a single string: `[ "$(cat $xfile_egpu | grep -Ei 'Driver' | cut -f 2 -d \")" != "nvidia" ]`

You may want to find a different way to determine if the returned values _contain_ "nvidia" instead, however - though I don't know exactly what it's used for. I don't have an nvidia card, so I suppose I could've just replaced it with `true` to the same effect, heh.

**Comment by hertg** [comment]
closed with #57
