### ISSUE TITLE
line 116: 16#0:: syntax error in expression (error token is ":")

### ISSUE THREAD

**Issue by woodspire** [hertg/egpu-switcher#59]
Brand new install of Ubuntu 20.10

Laptop: HP Spectre x360 13 aw-2020ca
Intel Xe graphics
16 GB RAM
thunderbolt 4
Razer Core X
Nvidia GeForce 1060

**Comment by woodspire** [comment]
lspci -d ::0300 && lspci -d ::0302
0000:00:02.0 VGA compatible controller: Intel Corporation UHD Graphics (rev 01)
0000:03:00.0 VGA compatible controller: NVIDIA Corporation GP106 [GeForce GTX 1060 6GB] (rev a1)

**Comment by woodspire** [comment]
quick hack:

declare name=$(echo $line | grep -o -e "[^:]*$")
declare bus=$(echo $line | grep -o -e "^[^ ]*")

# hack here
bus=${bus:2}

# The bus IDs in hex
declare bus1h=${bus:0:2}
declare bus2h=${bus:3:2}
declare bus3h=${bus:6:1}

**Comment by hertg** [comment]
> lspci -d ::0300 && lspci -d ::0302
> 0000:00:02.0 VGA compatible controller: Intel Corporation UHD Graphics (rev 01)
> 0000:03:00.0 VGA compatible controller: NVIDIA Corporation GP106 [GeForce GTX 1060 6GB] (rev a1)

quick question, does it print out the domain `0000` on your system?
Heres the output of the exact same command on my laptop:
```
00:02.0 VGA compatible controller: Intel Corporation UHD Graphics 630 (Mobile)
01:00.0 VGA compatible controller: NVIDIA Corporation GP107M [GeForce GTX 1050 Ti Mobile] (rev a1)
09:00.0 VGA compatible controller: NVIDIA Corporation GP104 [GeForce GTX 1080] (rev a1)
```

If so, what version is your installed `pciutils`? I'm on `3.7.0-1`.

**Comment by engelmeierpaul** [comment]
I'm on Fedora 34, `pciutils 3.7.0-3` and my  `lspci -d ::0300 && lspci -d ::0302` output is:
```
0000:00:02.0 VGA compatible controller: Intel Corporation TigerLake-LP GT2 [Iris Xe Graphics] (rev 01)
0000:3b:00.0 VGA compatible controller: NVIDIA Corporation GP107 [GeForce GTX 1050 Ti] (rev a1)
```

So `0000` for me as well. I've done a little research, and the [linux man page](https://linux.die.net/man/8/lspci) suggests using `lspci -mm` for script use.

`lspci -mm -d ::0300 && lspci -mm -d ::0302`:
```
00:02.0 "VGA compatible controller" "Intel Corporation" "TigerLake-LP GT2 [Iris Xe Graphics]" -r01 "Dell" "Device 0991"
3b:00.0 "VGA compatible controller" "NVIDIA Corporation" "GP107 [GeForce GTX 1050 Ti]" -ra1 "ASUSTeK Computer Inc." "Device 85d3"
```

This looks correct to me, and I believe this should work on any other distro too. So I'll go ahead and submit a pull request with the change.

**Comment by engelmeierpaul** [comment]
I should have read the whole man page. `lspci`, by default, suppresses domain numbers if the machine only has the domain `0`. By using the flag `-D` the PCI domain numbers will always be shown. I will implement this rather than `-mm` as it will require smaller changes in your code.

**Comment by hertg** [comment]
Nice, thanks for investigating this issue!
Using the `-D` option makes sense.

But there is still an issue now if the video card is on a non-zero domain, because the domain part is simply ignored right now.

To fix that, we have to store the domain and put it in the `BusID` option in `xorg.conf`.
Here is the relevant paragraph from the manpage (`man xorg.conf`):

```
BusID  "bus-id"
        This specifies the bus location of the graphics card.  For PCI/AGP cards,  the  bus-id
        string  has  the form PCI:bus@domain:device:function (e.g., "PCI:1@0:0:0" might be ap-
        propriate for an AGP card). The "@domain" part can be left out for PCI domain 0.  This
        field  is usually optional in single-head configurations when using the primary graph-
        ics card.  In multi-head configurations, or when using a secondary graphics card in  a
        single-head  configuration,  this  entry is mandatory.  Its main purpose is to make an
        unambiguous connection between the device section and the hardware it is representing.
        This information can usually be found by running the pciaccess tool scanpci.
```

So we probably need to add the `@domain` part in the `xorg.conf`.

That being said, I'll merge your PR, because it already resolves the issue to some degree. The problem with video-cards on a non-zero domain can be addressed later, I'll open a new issue for that. :smile:
