### ISSUE TITLE
Repository don't have Release file

### ISSUE THREAD

**Issue by antonino-tocco** [hertg/egpu-switcher#6]
Hi, I receive this error when try to add repository:
The repository haven't a release file.
I'm using Ubuntu 18.10.

Ca you help me?

**Comment by hertg** [comment]
Hi,
This might be because the project was only released for Ubuntu `18.04` and `19.04`.
Please consider upgrading to `19.04` since `18.10`s [End of Life is set for July, 2019](https://wiki.ubuntu.com/Releases).

Please report back if the problem still persists after upgrading.
