### ISSUE TITLE
eGPU always shows as disconnected

### ISSUE THREAD

**Issue by Sandvich** [hertg/egpu-switcher#60]
Hi,
For some reason, no matter what I do my eGPU is always shown as disconnected in eGPU switcher. Even if I plug it in before turning on the laptop.
I've checked boltctl and lspci and both show the card as expected, but the switcher just... Can't find it.

```
❯ sudo egpu-switcher switch auto
[info] Automatically detecting if egpu is connected... 
[info] EGPU is disconnected.
[info] Create symlink /etc/X11/xorg.conf -> /etc/X11/xorg.conf.internal
```
My thunderbolt security is set to none, and I believe ACL is on (but if you think that might affect it, I'll double check).

Troubleshooting questions:
- Installed via git + make
- Running Fedora 33
- Using a Dell XPS 13 (2019 2 in 1 model, I think it's the 7390?)
- Enclosure is a Razer Core X Chroma
- I'm using the AMDGPU drivers, v19.1.0 from the Fedora repos
- I'm using KDE + SSDM

This is the relevant bit of boltctl:
```
 ● Razer Core X Chroma
   ├─ type:          peripheral
   ├─ name:          Core X Chroma
   ├─ vendor:        Razer
   ├─ uuid:          00f18224-bce3-2701-ffff-ffffffffffff
   ├─ generation:    Thunderbolt 3
   ├─ status:        authorized
   │  ├─ domain:     d1465934-070e-8680-ffff-ffffffffffff
   │  ├─ rx speed:   40 Gb/s = 2 lanes * 20 Gb/s
   │  ├─ tx speed:   40 Gb/s = 2 lanes * 20 Gb/s
   │  └─ authflags:  none
   ├─ authorized:    Thu 25 Feb 2021 15:10:35 UTC
   ├─ connected:     Thu 25 Feb 2021 15:10:35 UTC
   └─ stored:        Wed 24 Feb 2021 16:11:42 UTC
      ├─ policy:     iommu
      └─ key:        no

 ● Razer Core X Chroma #2
   ├─ type:          peripheral
   ├─ name:          Core X Chroma
   ├─ vendor:        Razer
   ├─ uuid:          00536824-bce3-2701-ffff-ffffffffffff
   ├─ generation:    Thunderbolt 3
   ├─ status:        authorized
   │  ├─ domain:     d1465934-070e-8680-ffff-ffffffffffff
   │  ├─ rx speed:   40 Gb/s = 2 lanes * 20 Gb/s
   │  ├─ tx speed:   40 Gb/s = 2 lanes * 20 Gb/s
   │  └─ authflags:  none
   ├─ authorized:    Thu 25 Feb 2021 15:10:36 UTC
   ├─ connected:     Thu 25 Feb 2021 15:10:36 UTC
   └─ stored:        Wed 24 Feb 2021 16:19:49 UTC
      ├─ policy:     iommu
      └─ key:        no
```
(Not sure why it appears twice, maybe that's part of the issue?)
And lspci:
```
2e:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Hawaii XT / Grenada XT [Radeon R9 290X/390X] (rev 80)
2e:00.1 Audio device: Advanced Micro Devices, Inc. [AMD/ATI] Hawaii HDMI Audio [Radeon R9 290/290X / 390/390X]
```

**Comment by hertg** [comment]
Thanks for submitting all the information.

Have you tried re-running the setup? Maybe the card is connected to another PCI BUS ID than it was when you initially ran the setup. Can you post the outputs of the following commands?

This will output your egpu-switcher configuration (ie. at which PCI BUS ID egpu-switcher will look for your eGPU):
```shell
cat /etc/egpu-switcher/egpu-switcher.conf
```

This is the exact command egpu-switcher uses for egpu detection internally:
```shell
lspci -d ::0300 && lspci -d ::0302
```

**Comment by Sandvich** [comment]
Seems right:
```
❯ cat /etc/egpu-switcher/egpu-switcher.conf
external_driver=amdgpu
external_gpu=48:0:0
internal_driver=
internal_gpu=
❯ lspci -d ::0300 && lspci -d ::0302
00:02.0 VGA compatible controller: Intel Corporation Iris Plus Graphics G7 (rev 07)
2e:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Hawaii XT / Grenada XT [Radeon R9 290X/390X] (rev 80)
```
Also, I rebooted, so have a picture of the UEFI too :)
![image](https://user-images.githubusercontent.com/5482185/109189358-d99c7100-778b-11eb-9f06-d8d445541e37.png)

I've just rerun the setup, so I'll reboot now and see if it worked.

**Comment by Sandvich** [comment]
That got it! I did a little bit of digging and it looks like it was to do with the order that I plugged things in - I have both a dock and the enclosure, and if I plug in the enclosure first it seems to cause this issue.
Thanks!

**Comment by hertg** [comment]
```
❯ cat /etc/egpu-switcher/egpu-switcher.conf
external_driver=amdgpu
external_gpu=48:0:0
internal_driver=
internal_gpu=
❯ lspci -d ::0300 && lspci -d ::0302
00:02.0 VGA compatible controller: Intel Corporation Iris Plus Graphics G7 (rev 07)
2e:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Hawaii XT / Grenada XT [Radeon R9 290X/390X] (rev 80)
```

yes, you might have swapped the Thunderbolt 3 port where you connected those.

`2e:00.0 VGA compatible...` if you have a closer look here `2e` in HEX is `46` in DEC, but egpu-switcher was set up to search at BUS ID `48` :)

This will be addresses in the future, so that the PCI BUS ID no longer matters for egpu-switcher to detect your eGPU. For the time being, if you run into the problem again, just try re-running the setup.
