### ISSUE TITLE
Release ubuntu 21.04 package

### ISSUE THREAD

**Issue by rvanlaar** [hertg/egpu-switcher#64]
Could you add support for ubuntu 21.04 via packages.
It currently won't install on it. Here's the message log when running apt-get update after adding the ppa.

> E: The repository 'http://ppa.launchpad.net/hertg/egpu-switcher/ubuntu hirsute Release' does not have a Release file.
> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> N: See apt-secure(8) manpage for repository creation and user configuration details.

Note: The 20.10 packages work perfectly on 21.04.

**Comment by hertg** [comment]
I copied the binaries to the `Hirsute` series on launchpad, it should be available now.
