### ISSUE TITLE
can't get eGPU working on Ubuntu20.04 ( Aorus GTX 2080TI Gaming Box )

### ISSUE THREAD

**Issue by tpzou** [hertg/egpu-switcher#67]
Hi,

I recently purchased an external GPU, specifically the GIGABYTE Aorus GTX 2080ti Gaming Box to use with my laptop, I have a Dell G5 RTX2060 running Ubuntu 20.04. And my egpu can be authorized but can’t be used.

I try to reinstall the nvidia driver to suit both of gpu, but it is helpless. Everything seems to be normal, but the **nvidia-smi** can't recognize the egpu and I can't use it....

 Can anyone help me? Thanks.

![2021-07-09_20-18](https://user-images.githubusercontent.com/54886980/125076934-1d689500-e0f3-11eb-9784-1ab8f91b83be.png)
![image](https://user-images.githubusercontent.com/54886980/125077022-35401900-e0f3-11eb-9f18-da73c2f8fe5d.png)
![image](https://user-images.githubusercontent.com/54886980/125077203-6882a800-e0f3-11eb-9df5-aa495cabf130.png)

**Comment by hertg** [comment]
Have you only executed the `config` command?
You should run `egpu-switcher setup` rather than `egpu-switcher config`.
The config command only configures egpu-switcher (ie. saves your inputs), only the setup command will then actually create the necessary xorg configurations.

**Comment by tpzou** [comment]
> Have you only executed the `config` command?
> You should run `egpu-switcher setup` rather than `egpu-switcher config`.
> The config command only configures egpu-switcher (ie. saves your inputs), only the setup command will then actually create the necessary xorg configurations.

Thanks for your reply,
I have run `egpu-switcher setup`.  I run `egpu-switcher config`, because whenI rerun it, itprompted me that I should do this again,
