### ISSUE TITLE
`make uninstall` deletes the entire `/usr/bin`

### ISSUE THREAD

**Issue by yassineim** [hertg/egpu-switcher#7]
![IMG_20190824_160622](https://user-images.githubusercontent.com/9938439/63639316-925e8d00-c689-11e9-9229-40fc2e1e6128.jpg)

**Comment by hyphone** [comment]
this is serious!

the unsinstall script removes the whole /usr/bin dir!

`
BINDIR := /usr/bin
[...}
uninstall:
	rm -rfd ${DESTDIR}${BINDIR}
[...}
`

**Comment by hertg** [comment]
Oh wow, how did i fuck that one up. I'm so sorry for that!
@hyphone Thanks alot for the fast PR, just merged it and will release a new version asap.

**Comment by yassineim** [comment]
No problem, I used the occasion to try out openSUSE and it's great

**Comment by hertg** [comment]
Just released a new version and uploaded the fix to the ppa.
I've mentioned the bug in the readme for anyone thats still on an older version.
@yassineim Thank you for reporting the issue and sorry for the inconvenience, and thanks to @hyphone for the fast PR.
