### ISSUE TITLE
eGPU with External Monitor leads to frame copy via iGPU before displaying causing performance loss

### ISSUE THREAD

**Issue by crxssrazr93** [hertg/egpu-switcher#75]
The issue:

Trying to run any game results in frames being copied from eGPU, and sent to iGPU before displaying on External Monitor (which is directly connected to eGPU).

It is non-existent on Win10.

I can confirm however, that Xorg & games did run under eGPU (via nvidia-smi), however, running 

`lspci -v | grep VGA`

resulted in;
```
0000:00:02.0 VGA compatible controller: Intel Corporation TigerLake-LP GT2 [Iris Xe Graphics] (rev 01) (prog-if 00 [VGA controller])
0000:03:00.0 VGA compatible controller: NVIDIA Corporation GP106 [GeForce GTX 1060 6GB] (rev a1) (prog-if 00 [VGA controller])
```

Is there a way to disable iGPU from loading upon logging in so I can make further tests?

= Basic Info =

> Did you install `egpu-switcher` via ppa or via git + make
via DNF

OS: Fedora release 35 (Thirty Five) x86_64 
Host: 20VE ThinkBook 15 G2 ITL 
Kernel: 5.14.16-302.fsync.fc35.x86_64 
DE: KDE Plasma 5.22.5 
WM: KWin
Display Server:  x11
CPU: 11th Gen Intel i7-1165G7 (8) @ 4.700GHz 
GPU: Intel TigerLake-LP GT2 [Iris Xe Graphics] 
eGPU: ADT-Link via TB4 with GTX 1060 6GB

**Comment by hertg** [comment]
I'm not sure if that's an issue related to egpu-switcher.
How did you confirm that there is a "frame-copy" happening?

The internal graphics will always show up in `lspci`, even if they aren't used. Because the command shows all pci devices that are detected and exposed by the kernel in `/sys`. All egpu-switcher really does is making sure Xorg uses your eGPU if you bootup with your eGPU connected. Since you can confirm that Xorg and your games run via eGPU, it seems like egpu-switcher did its job.

Unfortunately, I may not be able to assist you much further on this issue. You might be able to get help on [egpu.io](https://egpu.io/forums/) as the community there is very friendly and knowledgeable.

**Comment by curiousercreative** [comment]
@hertg perhaps I should create a new issue, but I am  experiencing a similar issue (not sure if it's frame copying or what) with similar hardware (Intel i7-1165g7 w/ NVIDIA 1080 Ti eGPU). I'm able to install and configure and login, but my GPU shows 90% utilization and 75% PCIe bandwidth utilization while the Xorg process is consuming 90% CPU time all resulting in terrible performance. FWIW, I've separately had great luck running high performance eGPU on Wayland with the help of [all-ways-egpu](https://github.com/ewagner12/all-ways-egpu) but sadly the multi-monitor fractional scaling blurriness on Wayland leaves me wanting X11 to work for me right now.

System76 Galago Pro (galp5)
Pop!_OS 22.04
GNOME 42.1

**Comment by curiousercreative** [comment]
For me, this issue appears to have been caused by a config file that I created (following some forum advice). After disabling the config file, performance is as expected! Perhaps  @crxssrazr93 has a similar config somewhere in `/etc/X11/xorg.conf.d/`?

```
$ cat /etc/X11/xorg.conf.d/20-intel.conf.bak 
Section "Device"
    Identifier "Intel"
    Driver "intel"
    Option "TearFree"    "true"
EndSection
```

**Comment by crxssrazr93** [comment]
@curiousercreative While I cannot comment on whether or not that was the cause, I can say that at the time when 11th Gen iGPU driver support wasn't solid, so that config was needed to prevent screen tear. Presently, I don't use it, but I also don't have an EGPU setup to test too.
