### ISSUE TITLE
Missing 21.10 Impish PPA Distributable

### ISSUE THREAD

**Issue by mraxilus** [hertg/egpu-switcher#76]
I get a 404 when trying to add the PPA.

Looking at the launchpad folder, I can confirm the latest is only hirstule: `http://ppa.launchpad.net/hertg/egpu-switcher/ubuntu/dists/`

- Did you install `egpu-switcher` via ppa or via git + make: ppa
- What Linux distribution (+ version) are you using: PopOs 21.10
- What brand / model is your laptop: System76 Galago Pro
- What brand / model is your GPU (+ enclosure): Razer Core X Chroma, 3080 EVGA FW3 Ultra
- What drivers (+ version) are you using: 470.86
- What Desktop-Environment do you use (+ Display-Manager): Gnome

**Comment by hertg** [comment]
You're right, sorry about that.

I keep forgetting that the package needs to be re-published for every Ubuntu version specifically. I think launchpad is the least user-friendly publishing platform I've ever used :stuck_out_tongue_closed_eyes: But I think a lot of users are glad it's available via PPA, so I'll try my best to maintain the package there.

I've copied the binaries over to the `Impish` Series and also to the upcoming `Jammy` series, to prevent the same issue from happening next spring. :)

Please let me know if something isn't working.

**Comment by mraxilus** [comment]
Thanks, resolved. Awesome project by the way; it makes my life so much easier.
