### ISSUE TITLE
Broken after upgrade to Pop!_OS 21.10 on Lenovo X1 Extreme Gen 2

### ISSUE THREAD

**Issue by MattInternet** [hertg/egpu-switcher#78]
Background:
- Installed via ppa
- Pop!_OS 21.10 Kernel 5.16.15
- Lenovo X1 Extreme Gen 2 (Thunderbolt 3)
- Proprietary Nvidia driver Ver 510.54
- DE: GNOME 40.5
- WM: Mutter

Internal GPU(s):
- Intel UHD Graphics 630
- Nvidia GTX 1650 Mobile / Max-Q

External GPU:
- GTX 980 Ti in HP Accelerator chassis

I've been using egpu-switcher successfully for a long time under Popos 20.10 and I think even under 20.04 before that. Since the upgrade to 21.10 though I cannot get my egpu to render anything on the 2 displays attached to it. The closest I can get now is a blank screen with a blinking prompt after the system is booted with the eGPU attached. If i remove the eGPU and boot I can login just fine and run `sudo egpu-switcher cleanup`.

I have enabled Pre-Boot ACL and the TB security mode is set to `user` according to `boltctl`

If I boot from a clean install with the eGPU attached I can see the GPU in both `nvidia-smi` and when using `egpu-switcher setup`. I have also tried `egpu-switcher setup --override` and even tried adding a sleep to the systemd service as per #67 

After running `egpu-switcher setup` my monitors do have their backlights turn on for a moment before saying `No DP detected` and turning back off. Also once I get to the blank screen with the blinking prompt i cannot login even via a virtual terminal. Ill get the login prompt for a couple of seconds then it goes back to the blinking cursor.

Sorry for the massive issue I just wanted to give as much context as possible and to see if i can avoid going back to 20.04...

**Comment by MattInternet** [comment]
In the Pop!_OS settings and in the BIOS I also have discrete graphics selected, not hybrid.

**Comment by MattInternet** [comment]
I think the issue was actually caused by nvidia drivers at version 510. I downgraded to 470 (470.86 to be exact) and everything works!

**Comment by hertg** [comment]
@MattInternet 
Sorry for the late response. Glad you were able to resolve it, and thank you for reporting back your solution. It may help someone in future troubleshoots.
