### ISSUE TITLE
Wrong driver for amd egpu

### ISSUE THREAD

**Issue by TheBlob42** [hertg/egpu-switcher#81]
While setting up my egpu with the help of your wonderful script I ran into a problem. The setup process worked smoothly and the egpu was detected, but on boot with the egpu plugged in I was presented with a black screen and a blinking cursor. Checking the issues here and the troubleshooting document I tried implementing a slight delay like in #77 or #50, but that did not help. I activated `Pre-Boot ACL` but that also did not change anything...

When checking the output of `lspci -k` I saw the the kernel driver in use was `radeon`. Checking the generated `xorg.conf.egpu` file I saw the the value for `Driver` was set to `amdgpu`. Changing this value to `radeon` finally did the trick for me and now my setup is working as it should.

Is this "wrong" driver detection something which could be fixed in the script somehow?  
Or would it make sense to add this problem to the troubleshooting document within this repository?

**Comment by hertg** [comment]
hmm, good point. What GPU are you using?
I'm currently rewriting egpu-switcher, I'll take that feedback into consideration and make sure to address it

**Comment by TheBlob42** [comment]
I am using an old `AMD Radeon R9 280x`
