### ISSUE TITLE
Mention golang as build requirement in README

### ISSUE THREAD

**Issue by Samcpfc** [hertg/egpu-switcher#98]
- Fedora 37
- Razer Blade 2019

Trying to install egpu-switcher on Fedora 37, using git+make. Whenever I run "make build -s" i get an error.  Fairly new to Linux so still have a lot to learn. Help would be appreciated. Thanks

```
/bin/sh: line 1: go: command not found
make: *** [Makefile:25: build] Error 127
```

**Comment by hertg** [comment]
Hey there, You need to [install the go toolchain](https://go.dev/doc/install) on your computer in order to compile the application. I should probably mention that explicitly in the README somewhere, thanks for pointing it out.

**Comment by hertg** [comment]
Btw, you can probably just install it via your package manager instead of downloading it from the website I linked. I'm not too familiar with fedora, but it seems to be available as `golang`.

```
sudo dnf install golang
```

**Comment by Samcpfc** [comment]
Fantastic. I was losing my mind over this. Really appreciate the help, got it all installed now. Thanks.
